# Numpy

Numpy is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays.

To use Numpy, we first need to import the `numpy` package:

In [1]:
import numpy as np

## Arrays

A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. The number of dimensions is the rank of the array; the shape of an array is a tuple of integers giving the size of the array along each dimension.

We can initialize numpy arrays from nested Python lists:

In [2]:
# A rank 1 array
a = np.array([1, 2, 3])
print(a, type(a))

[1 2 3] <class 'numpy.ndarray'>


and access elements using square brackets:

In [3]:
a[1] = 0
a

array([1, 0, 3])

In [4]:
a.shape

(3,)

In [5]:
a[2]

3

In [6]:
# A rank 2 array
b = np.array([[1, 2, 3], [4, 5, 6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
b.shape

(2, 3)

In [8]:
b[0, 1]

2

Numpy also provides many functions to create arrays:

In [9]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
a = np.zeros((2,2))  # Create an array of all zeros
print(a)

[[0. 0.]
 [0. 0.]]


In [11]:
b = np.ones((1,2))   # Create an array of all ones
print(b)

[[1. 1.]]


In [12]:
c = np.full((2,2), 7) # Create a constant array
print(c)

[[7 7]
 [7 7]]


In [13]:
d = np.random.random((2,2)) # Create an array filled with random values
print(d)

[[0.35423911 0.15886842]
 [0.2276366  0.65440483]]


Arrays can be flattened, resulting in a rank 1 array:

In [14]:
d.flatten()

array([0.35423911, 0.15886842, 0.2276366 , 0.65440483])

## Array operations

One difference between python lists and numpy arrays is the element-wise operations:

In [15]:
a = [1, 2, 3]
b = [4, 5, 6]

In [16]:
# adding two basic python lists
a + b

[1, 2, 3, 4, 5, 6]

In [17]:
# adding two numpy arrays
np.array(a) + np.array(b)

array([5, 7, 9])

Also other operations are done element-wise, such as cos, sin, tan, sqrt, exp, log, etc..

In [18]:
np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

In [19]:
np.exp(a)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [20]:
np.sqrt(b)

array([2.        , 2.23606798, 2.44948974])

### Assignment 1
Multiply a and b element-wise without using numpy

In [21]:
# unfortunately this does not work
c = a*b

TypeError: can't multiply sequence by non-int of type 'list'

In [22]:
# create an empty list to store the results
c = []

# loop through and multiply elements and append the result to c
for i in range(len(a)):
    result = ...
    c.append(result)

print(c)

[Ellipsis, Ellipsis, Ellipsis]


### Assignment 2
Multiply a and b using numpy

In [23]:
d = ...

print(d)

Ellipsis


### Assignment 3
Calculate the cross sectional area for pipes with outer diameters 10 to 100 millimeters with a 10 millimeter step (10, 20, 30 etc). The wall thickness is 20% of the outer diameter.

In [24]:
outer = np.arange(10, 110, 10)
...
area = ...

print(area)

Ellipsis


### Assignment 4
Numpy arrays are also useful for calculating inner and outer products of vectors. It is also possible to do basic matrix computation.

Using 3D coordinates as $\{x, y, z\}$, calculate the moment caused by 1 kg at the end of a 10 meter beam.

In [66]:
# force
F = np.array([0, 0, -9.81])
# radius
r = np.array([10, 0, 0])

# calculate the moment using the cross product of F and r
# np.something(F, r)
# moment should be around the y-axis